-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 16:49:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NULL,
  `prenom` VARCHAR(20) NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `statut` SMALLINT(10) NULL,
  `login` VARCHAR(20) NULL,
  `username` VARCHAR(20) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupe` (
  `idgroupe` INT NOT NULL AUTO_INCREMENT,
  `nomdugroupe` VARCHAR(45) NOT NULL,
  `administrateur` INT NOT NULL,
  `date_creation` TIMESTAMP NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idgroupe`),
  INDEX `fk_groupe_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_groupe_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asset` (
  `idasset` INT NOT NULL AUTO_INCREMENT,
  `nom_document` VARCHAR(45) NOT NULL,
  `date_creation` TIMESTAMP NULL,
  `descriptif` VARCHAR(45) NULL,
  `url` VARCHAR(200) NULL,
  `groupe_idgroupe` INT NOT NULL,
  PRIMARY KEY (`idasset`),
  INDEX `fk_asset_groupe1_idx` (`groupe_idgroupe` ASC) VISIBLE,
  CONSTRAINT `fk_asset_groupe1`
    FOREIGN KEY (`groupe_idgroupe`)
    REFERENCES `mydb`.`groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `asset_idasset` INT NOT NULL,
  PRIMARY KEY (`asset_idasset`),
  INDEX `fk_image_asset1_idx` (`asset_idasset` ASC) VISIBLE,
  CONSTRAINT `fk_image_asset1`
    FOREIGN KEY (`asset_idasset`)
    REFERENCES `mydb`.`asset` (`idasset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `asset_idasset` INT NOT NULL,
  PRIMARY KEY (`asset_idasset`),
  INDEX `fk_video_asset1_idx` (`asset_idasset` ASC) VISIBLE,
  CONSTRAINT `fk_video_asset1`
    FOREIGN KEY (`asset_idasset`)
    REFERENCES `mydb`.`asset` (`idasset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conversation` (
  `idconversation` INT NOT NULL AUTO_INCREMENT,
  `user_id_emetteur` INT NOT NULL,
  `user_id_recepteur` INT NOT NULL,
  PRIMARY KEY (`idconversation`),
  INDEX `fk_conversation_user1_idx` (`user_id_emetteur` ASC) VISIBLE,
  INDEX `fk_conversation_user2_idx` (`user_id_recepteur` ASC) VISIBLE,
  CONSTRAINT `fk_conversation_user1`
    FOREIGN KEY (`user_id_emetteur`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_user2`
    FOREIGN KEY (`user_id_recepteur`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `idmessage` INT NOT NULL,
  `conversation_idconversation` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `contenu_message` VARCHAR(45) NULL,
  `date_heure` TIMESTAMP NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_message_conversation1_idx` (`conversation_idconversation` ASC) VISIBLE,
  INDEX `fk_message_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_message_conversation1`
    FOREIGN KEY (`conversation_idconversation`)
    REFERENCES `mydb`.`conversation` (`idconversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membre` (
  `user_iduser` INT NOT NULL,
  `groupe_idgroupe` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `groupe_idgroupe`),
  INDEX `fk_user_has_groupe_groupe1_idx` (`groupe_idgroupe` ASC) VISIBLE,
  INDEX `fk_user_has_groupe_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_groupe_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_groupe_groupe1`
    FOREIGN KEY (`groupe_idgroupe`)
    REFERENCES `mydb`.`groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
